### ISSUE TITLE
Criação de um Projeto Exemplo do ms-clientes

### ISSUE THREAD

**Issue by lgshogun** [redmasters/alice#30]
## Informações:
- Ruby 3.0.2
- Rails 6.0
- Docker (com PostgreSQL).

Tendo em base o tutorial: https://dev.to/joker666/deploy-a-ruby-on-rails-api-only-application-in-docker-with-postgresql-1933

## To-do:
- [X] Criação do bundle do ruby on rails.
- [X] Construção dos `resources` Cliente, com os campos nome, date_nascimento, endereco.
- [X] Construção dos controllers.
- [X] Configuração de rotas.
- [X] Criação da configuração Docker com PostgreSQL e bota pra rodar.

## To-do Extras:
- [ ] Continuação da criação dos métodos RESTFUL e CRUD.
- [ ] Criação de validações para todos os campos.
